### ISSUE TITLE
Randomised beat settings let you 0% on all settings

### ISSUE THREAD

**Issue by br1noce** [RossMcMillan92/djent#2]
If you put 0% on all Randomised beat settings, wich it not make sense, and then you generate the riff, it will spin forever and you need to reload the page.
Console gives this error: Unhandled promise rejection There are no allowed lengths given app.min.js.pagespeed.jm.hNxTtRTfCR.js:1:44926
![2016-07-01_12-47-11](https://cloud.githubusercontent.com/assets/7023970/16527013/a9f4a8a2-3f8a-11e6-8a18-d3b43473ac38.png)
![2016-07-01_12-47-44](https://cloud.githubusercontent.com/assets/7023970/16527014/ac674b3a-3f8a-11e6-9a62-5bf866398f17.png)

**Comment by RossMcMillan92** [comment]
new sequence system fixes this
