### ISSUE TITLE
Making tracks

### ISSUE THREAD

**Issue by jzaefferer** [RossMcMillan92/djent#8]
This is pretty interesting, but I'm missing some way to "make a track". Something beyond looping a single riff or abruptly stopping one riff when another starts.

Here's some ideas to "solve" this:
- When generating a new riff, let the current one finish playing, and replace it with the new one at the right moment. That would allow live mixing tracks
- An export option, where I could download multiple pieces and then put them together elsewhere
- A track editor, where I can generate multiple riffs and put one after the other. This seems by far the most out of scope

**Comment by RossMcMillan92** [comment]
Late to this one, but multiple tracks now exist. Closing.
